import pandas as pd
# dùng để chuyển tên cột để phù hợp với database
import_column_mapping = {
  "date":"trade_date",
  "billid": "bill_id",
  "trans":"transportation",
  "bill_no":"b/l_number_or_awb_number",
  "hs":"hs_code",
  "descript":"products",
  "importer_code":"importer_code",
  "buyer":"buyer",
  "seller":"supplier",
  "amount":"total_value_USD",
  "price":"unit_price_currency",
  "amount_currency":"currency",
  "total_value":"total_value_currency",
  "qty":"quantity",
  "quantity_unit":"quantity_unit",
  "import_tax_amount":"import_tax",
  "fob_amount":"fob_usd",
  "cif_amount":"cif_usd",
  "weight":"gross_weight_kg",
  "weight_unit":"weigh_unit",
  "buyer_country":"destination_country",
  "seller_port":"loading_port",
  "origin_country":"country_of_origin",
  "flight_vessel_code":"flight/voyage_number",
  "vn_port_customs_warehouse_name":"customs_warehouse_name_in_vietnamese_port",
  "address_of_exporter":"supplier_address",
  "vnd_exchange_rate": "exchange_rate",
  "vietnam_importer_address": "buyer_address",
  "importer_telephone_number":"buyer/supplier_tel",
  "import_port":"export_port",
  "buyer_port":"import_port",
  "name_of_customs":"customs",
  "seller_country" :"supplier_country",
  "uusd" :"unit_price_usd",
}



# tổng số lượng cột
all_columns = ['bill_id', 'Buyer', 'Supplier', 'Total Value(USD)', 'Products',
'Trade Date', 'Unit Price(Currency)', 'Currency', 'Supplier address',
'Exchange rate', 'B/L Number Or AWB Number', 'Flight/Voyage Number',
'Customs Warehouse Name In Vietnamese Port',
'Export/Import Declaration Number', 'Country of Origin', 'HS Code',
'Export Port', 'Quantity', 'Quantity Unit', 'Incoterms',
'Importer Code', 'Total Value(Currency)', 'Method Payment',
'Buyer address', 'Import Tax', 'Landing port', 'Gross Weight(KG)',
'Weight Unit', 'Destination country', 'FOB(USD)', 'CIF(USD)',
'Transportation', 'Buyer (Import)/ Supplier (Export) tel', 'Customs',
'Port of loading', 'Type_transaction']

# tên cột trước khi đổi, dùng để chuẩn hóa khi lưu tạm dữ liệu vào file csv
raw_import_header=[
  "hs",
  "trans",
  "price",
  "descript",
  "date",
  "origin_country",
  "bill_no",
  "total_value",
  "weight_unit",
  "incoterms",
  "buyer",
  "quantity_unit",
  "buyer_port",
  "seller",
  "importer_std",
  "declaration_number",
  "import_tax_amount",
  "name_of_customs",
  "importer_code",
  "amount",
  "importer_telephone_number",
  "seller_port",
  "buyer_country",
  "uusd",
  "vnd_exchange_rate",
  "bill_id",
  "amount_currency",
  "billid",
  "flight_vessel_code",
  "fob_amount",
  "vietnam_importer_address",
  "cif_amount",
  "qty",
  "payment_method",
  "address_of_exporter",
  "seller_country",
  "weight",
  "vn_port_customs_warehouse_name",

]
# dùng để kiểm tra và loại bỏ các cột không cần thiết
column_to_keep = [
  "date",
  "bill_id",
  "trans",
  "bill_no",
  "hs",
  "descript",
  "importer_code",
  "buyer",
  "seller",
  "amount",
  "price",
  "amount_currency",
  "total_value",
  "qty",
  "quantity_unit",
  "import_tax_amount",
  "fob_amount",
  "cif_amount",
  "weight",
  "weight_unit",
  "buyer_country",
  "incoterms",
  "payment_method",
  "seller_port",
  "origin_country",
  "flight_vessel_code",
  "vn_port_customs_warehouse_name",
  "name_of_customs",
  "declaration_number",
  "uusd",
  "vietnam_importer_address",
  "address_of_exporter"
  "declaration_number",
  "importer_telephone_number",
  ]